// Prompt loaders for the Phase 1 / Stage 1 question extractor
// (scripts/pdf-pipeline/extract-with-gemini.mjs).
//
// Stage 1 is a dedicated, source-faithful SAT question extractor. Its
// prompts live as standalone files (easy to review/diff in isolation,
// and asserted on by extraction-prompt.test.ts) rather than inline:
//
//   · question-imports/prompts/stage1-extraction-system.txt
//       The extraction-only SYSTEM prompt: role, scope, prohibitions,
//       the fixed enums, and the output contract. NOT the old
//       all-in-one KarmanGPT.txt (which also carried CSV / explanations
//       / hints / Desmos / image handling — downstream concerns that
//       conflict with a Stage 1 extractor). KarmanGPT.txt is retained
//       as a legacy/manual reference; it is no longer the active prompt.
//
//   · question-imports/prompts/stage1-extraction-user.md
//       The USER prompt: detailed per-question extraction rules + the
//       single { "questions": [...] } output contract. Parameterized on
//       the source PDF filename via the {{source_pdf}} placeholder.
//
//   · scripts/lib/prompts/taxonomy-fragment.txt
//       The canonical 8-domain / 8-cluster / 89-slug taxonomy, appended
//       to the system prompt at load time. Auto-generated by
//       scripts/sync-taxonomy.ts (npm run sync:taxonomy) from
//       src/data/curriculum/*.ts — the single source of truth. Do not
//       hand-edit it here.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const PROMPT_DIR = join(HERE, "../../question-imports/prompts");
const TAXONOMY_FRAGMENT_PATH = join(HERE, "prompts/taxonomy-fragment.txt");

/**
 * Build the Stage 1 USER prompt for a given source PDF.
 *
 * Loads the user-prompt template and substitutes the exact PDF filename
 * for every {{source_pdf}} placeholder. The filename is used only as
 * source metadata — the prompt instructs the model not to infer content
 * from it.
 *
 * Pure given the file on disk: same template + same pdfName → same string.
 */
export function buildUserPrompt(pdfName) {
  const template = readFileSync(join(PROMPT_DIR, "stage1-extraction-user.md"), "utf8");
  return template.replaceAll("{{source_pdf}}", pdfName);
}

/**
 * Build the USER prompt for one IMAGE BATCH of the page-image extractor
 * (extract-with-images.mjs). Unlike buildUserPrompt (whole PDF via parsed
 * text, with the ~98-count framing), this targets a SUBSET of rendered
 * pages: the model is shown N page images and extracts every question
 * visible in them. Total-count expectations do NOT apply per batch —
 * completeness is enforced at merge time across all batches. The system
 * prompt (loadStage1SystemPrompt) still supplies the role, enums, and
 * 89-slug taxonomy.
 *
 * pages: array of 1-based PDF page numbers, in the SAME order the images
 * are attached to the message (image 1 = pages[0], etc.).
 */
export function buildPageBatchUserPrompt(pages) {
  const list = pages.join(", ");
  return `TASK: Extract EVERY SAT question visible in the attached page images into structured JSON.

THE IMAGES:
You are given ${pages.length} page image(s) from an SAT practice-test PDF, attached in order. They are PDF pages ${list} (image 1 = page ${pages[0]}). This is only a SUBSET of the whole test — extract only what is visible here. Do NOT invent questions for pages you cannot see, and do NOT try to reach any total question count; completeness is checked after all batches merge.

OUTPUT CONTRACT:
Return ONLY one top-level JSON object: { "questions": [ ... ] }
No other top-level keys, no prose, no Markdown.

WHICH PAGES ARE QUESTIONS:
- A page showing a question stem (plus A-D choices, for multiple choice) is a question — extract it.
- Skip pure directions/instructions, section-intro, and break screens, and answer-key tables with no question.
- If a page shows only PART of a question that continues from / onto an adjacent visible page (e.g. a repeated figure + the remaining choices), MERGE it into the one question; do not emit a duplicate.

FIELDS (emit exactly these; the system instructions list the canonical enums + 89 concept slugs):
extraction_order, section, module_number, question_number, question_number_visible, question_text, choice_a, choice_b, choice_c, choice_d, correct_answer, difficulty, topic_cluster, passage, passage_intro, passage_a, passage_b, question_format, numeric_tolerance, domain, concept_slug, answer_source, source_page, has_figure, figure_alt, import_status, import_flag_reason.

KEY RULES:
- source_page: the PDF page the question is on — one of ${list}. Use the page order (image 1 = page ${pages[0]}).
- section + module_number: read the page header — "Section 1, Module 1: Reading and Writing" → section="reading_writing", module_number=1; "Section 2, Module 2: Math" → section="math", module_number=2.
- question_number: the per-module number printed on the page ("Question 8 of 27" → 8). It RESTARTS at 1 each module. question_number_visible = the same number as a string. Never use a global running count.
- extraction_order: 1, 2, 3, … in page order WITHIN this batch (a global order is reassigned after merge).
- READING & WRITING: stimulus goes in passage (or passage_a / passage_b for Text 1 / Text 2); question_text holds ONLY the stem. Never duplicate the passage into question_text.
- MATH: passage / passage_intro / passage_a / passage_b all "". Student-produced-response questions have NO A-D choices — set question_format="numeric_entry", leave choices "", and still extract them.
- domain must match section: R&W → info_ideas | craft_structure | expression_ideas | conventions; Math → algebra | advanced_math | geometry | data_analysis. data_analysis is a MATH domain — an R&W question that uses a table/graph as evidence is STILL R&W (info_ideas).
- correct_answer: these are STUDENT-ATTEMPT screenshots with NO official answer key. A highlighted/filled/selected choice is the STUDENT'S answer (often wrong, often blank) — NEVER copy it. SOLVE the question yourself and set answer_source="inferred". A downstream stage reconciles against the official key. Never use answer_source="extracted" (there is no key here). If you cannot solve it, set import_status="needs_review" + import_flag_reason="answer_uncertain".
- has_figure=true when the question depends on a visible graph/table/diagram; write a short figure_alt. Visual crop/render is a downstream stage.
- import_status="needs_review" with a specific import_flag_reason for anything unclear; otherwise "ok".

Preserve source text faithfully; use KaTeX for math (e.g. $x^2$, $\\frac{1}{2}$). Return only the JSON object.`;
}

/**
 * Build the Stage 1 SYSTEM prompt = the extraction-only base prompt with
 * the canonical taxonomy fragment appended. The taxonomy lists the only
 * legal values for domain / topic_cluster / concept_slug; the base
 * prompt covers the fixed question_format / answer_source / import_status
 * enums and the output contract.
 *
 * Moonshot/Kimi JSON-object mode does NOT enforce these — extract-with-
 * gemini.mjs post-validates every row (see extraction-validation.mjs).
 */
export function loadStage1SystemPrompt() {
  const base = readFileSync(join(PROMPT_DIR, "stage1-extraction-system.txt"), "utf8");
  const taxonomy = readFileSync(TAXONOMY_FRAGMENT_PATH, "utf8");
  return `${base.trimEnd()}\n\n${taxonomy.trimEnd()}\n`;
}
